name: docs

on: [push, pull_request]

# cancels prior builds for this workflow when new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and generate documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']
        ipopt-version: ['3.14']
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout CyIpopt
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: test-environment
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          conda-remove-defaults: "true"
          miniforge-version: latest
      - name: Install basic dependencies
        run: conda install -y -v lapack "libblas=*=*netlib" "cython>=0.29.37" "ipopt=${{ matrix.ipopt-version }}" numpy>=1.26.4 pkg-config>=0.29.2 setuptools>=68.1.2 --file docs/requirements.txt
      - name: Install CyIpopt
        run: |
          python -m pip install --no-deps --no-build-isolation .
          conda list
      - name: Test building documentation
        run: cd docs && make clean && make html && cd ..
