name: tests

on: [push, pull_request]

# cancels prior builds for this workflow when new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # TODO : Move to macos-latest which is an arm image, but then the old
        # ipopts will not be available, see: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        os: [ubuntu-latest, macos-13, windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        ipopt-version: ['3.13', '3.14']
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout CyIpopt
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: test-environment
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          conda-remove-defaults: "true"
          miniforge-version: latest
      - name: Install basic dependencies
        # NOTE : I had to return to installing the netlib packages, otherwise
        # the lapack.pc file was not present with all versions of ipopt
        # installed.
        run: |
          conda install -q -y "ipopt=${{ matrix.ipopt-version }}" "numpy>=1.26.4" "pkg-config>=0.29.2" "setuptools>=68.1.2" "cython>=0.29.37" "pytest>=7.4.4" "libblas=*=*_netlib"
      - name: Test pkg-config
        run: pkg-config --libs --cflags ipopt
      - name: Install cyipopt
        run: |
          rm pyproject.toml
          python -m pip install -v --no-deps --no-build-isolation .
          conda list
      - name: Test with pytest and run examples
        run: |
          python -c "import cyipopt"
          conda list
          pytest
          python examples/hs071.py
          python examples/exception_handling.py
      - name: Test with pytest and scipy, new ipopt
        run: |
          conda install -q -y -c conda-forge "ipopt=${{ matrix.ipopt-version }}" "numpy>=1.26.4" "pkg-config>=0.29.2" "setuptools>=68.1.2" "scipy>1.11.4" "pytest>=7.4.4" "cython>=0.29.37"
          conda list
          pytest
