name: windows

on: [push, pull_request]

# cancels prior builds for this workflow when new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Manually install on Windows with Ipopt binaries
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - run: python -m pip install "numpy>=1.26.4" "cython>=0.29.37" "setuptools>=68.1.2"
      - run: Invoke-WebRequest -Uri "https://github.com/coin-or/Ipopt/releases/download/releases%2F3.13.3/Ipopt-3.13.3-win64-msvs2019-md.zip" -OutFile "Ipopt-3.13.3-win64-msvs2019-md.zip"
      - run: 7z x Ipopt-3.13.3-win64-msvs2019-md.zip
      - run: mv Ipopt-3.13.3-win64-msvs2019-md/* .
      - run: python -m pip install --no-deps --no-build-isolation .
      - run: python examples/hs071.py
